[package]
name = "riscv_semi"
version = "0.1.0"
edition = "2024"

[dependencies]
riscv-rt = { git = "https://github.com/rust-embedded/riscv", branch = "master"}
panic-halt = "1.0.0"
semihosting = { version = "0.1", features = ["stdio", "panic-handler"] }